import { GoogleGenAI, Type, Schema } from "@google/genai";
import { Plan, AgentOutput, File } from "../types";
import { SESSION_SYSTEM_PROMPT, SESSION_PLANNING_PROMPT_TEMPLATE, ORCHESTRATOR_SYSTEM_PROMPT, AGENT_SYSTEM_PROMPT_TEMPLATE } from "./prompts";

const apiKey = process.env.API_KEY || '';
const genAI = new GoogleGenAI({ apiKey });

// --- Schema Definitions ---

const fileSchema: Schema = {
  type: Type.OBJECT,
  description: "Represents a generated file.",
  properties: {
    path: { 
      type: Type.STRING, 
      description: "File path or name (e.g., 'src/main.py')." 
    },
    content: { 
      type: Type.STRING, 
      description: "Full content of the file." 
    },
  },
  required: ["path", "content"],
  propertyOrdering: ["path", "content"],
};

const artifactSchema: Schema = {
  type: Type.OBJECT,
  description: "Output artifact generated by a task.",
  properties: {
    task: { 
      type: Type.STRING, 
      description: "ID of the task that produced this artifact (e.g., 'T-10.0')." 
    },
    files: {
      type: Type.ARRAY,
      items: fileSchema,
      description: "Files generated by the task.",
    },
  },
  required: ["task", "files"],
  propertyOrdering: ["task", "files"],
};

const roleSchema: Schema = {
  type: Type.OBJECT,
  description: "Definition of an agent's role and goal.",
  properties: {
    title: { 
      type: Type.STRING, 
      description: "Title of the role (e.g., 'Frontend Developer')." 
    },
    purpose: { 
      type: Type.STRING, 
      description: "Purpose of the role (e.g., 'Develop user interfaces')." 
    },
  },
  required: ["title", "purpose"],
  propertyOrdering: ["title", "purpose"],
};

const taskSchema: Schema = {
  type: Type.OBJECT,
  description: "A single actionable step in a plan.",
  properties: {
    id: { 
      type: Type.STRING, 
      description: "Unique ID for the task (e.g., 'T-00.1')." 
    },
    description: { 
      type: Type.STRING, 
      description: "Detailed description of what to do." 
    },
    role: { 
      type: Type.STRING, 
      description: "The role responsible for this task." 
    },
    agent: { 
      type: Type.STRING, 
      description: "The name of the agent assigned (e.g., 'Alice')." 
    },
    deps: { 
      type: Type.ARRAY, 
      items: { type: Type.STRING }, 
      description: "List of dependency task IDs." 
    },
  },
  required: ["id", "description", "role", "agent", "deps"],
  propertyOrdering: ["id", "description", "role", "agent", "deps"],
};

const promptSchema: Schema = {
  type: Type.OBJECT,
  description: "System prompt update for an agent.",
  properties: {
    agent: { 
      type: Type.STRING, 
      description: "Name of the agent." 
    },
    role: { 
      type: Type.STRING, 
      description: "Role context." 
    },
    system_prompt: { 
      type: Type.STRING, 
      description: "New system prompt content." 
    },
  },
  required: ["agent", "role", "system_prompt"],
  propertyOrdering: ["agent", "role", "system_prompt"],
};

const teamSchema: Schema = {
  type: Type.OBJECT,
  description: "Team coordination and updates.",
  properties: {
    notes: { 
      type: Type.STRING, 
      description: "General notes or feedback about the team's performance or the plan." 
    },
    prompts: { 
      type: Type.ARRAY, 
      items: promptSchema, 
      description: "List of new or updated system prompts for any agent in the team." 
    },
  },
  required: ["notes"],
  propertyOrdering: ["notes", "prompts"],
};

const planSchema: Schema = {
  type: Type.OBJECT,
  description: "The execution plan containing tasks, roles, and strategy.",
  properties: {
    high_level_goal: { 
      type: Type.STRING, 
      description: "The main goal." 
    },
    reasoning: { 
      type: Type.STRING, 
      description: "Explanation of the strategy." 
    },
    roles: { 
      type: Type.ARRAY, 
      items: roleSchema, 
      description: "Roles required for the plan." 
    },
    tasks: { 
      type: Type.ARRAY, 
      items: taskSchema, 
      description: "Sequence of tasks to execute." 
    },
    team: { 
        ...teamSchema,
        description: "Initial team configuration (optional)."
    },
  },
  required: ["high_level_goal", "reasoning", "roles", "tasks"],
  propertyOrdering: ["high_level_goal", "reasoning", "roles", "tasks", "team"],
};

const agentOutputSchema: Schema = {
  type: Type.OBJECT,
  description: "Structured output returned by an agent after executing a task.",
  properties: {
    output: { 
      type: Type.STRING, 
      description: "Text message content (response from agent)." 
    },
    reasoning: { 
      type: Type.STRING, 
      description: "Explanation of how the agent arrived at this output." 
    },
    artifact: {
        ...artifactSchema,
        description: "Files generated or modified by the agent (optional)."
    },
    team: {
        ...teamSchema,
        description: "Updates to team configuration or system prompts (optional)."
    },
  },
  required: ["output"],
  propertyOrdering: ["output", "reasoning", "artifact", "team"],
};

// --- Retry Logic ---

const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

const callWithRetry = async <T>(fn: () => Promise<T>, retries = 10, delay = 4000): Promise<T> => {
  try {
    return await fn();
  } catch (error: any) {
    const isRateLimit = error?.status === 429 || 
                        error?.code === 429 || 
                        error?.message?.includes('429') || 
                        error?.message?.includes('quota') || 
                        error?.message?.includes('RESOURCE_EXHAUSTED');
    
    if (isRateLimit && retries > 0) {
      console.warn(`Rate limit exceeded. Retrying in ${delay}ms... (${retries} retries left)`);
      await sleep(delay + Math.random() * 1000); // Add jitter
      return callWithRetry(fn, retries - 1, delay * 2);
    }
    throw error;
  }
};


export const generatePlan = async (goal: string, files: File[] = []): Promise<Plan> => {
  if (!apiKey) throw new Error("API Key not found");

  const model = "gemini-2.5-flash-lite";

  let sessionPlanningPrompt = SESSION_PLANNING_PROMPT_TEMPLATE
    .replace('{high_level_goal}', goal);

  return callWithRetry(async () => {
    try {
      const response = await genAI.models.generateContent({
        model,
        contents: [ sessionPlanningPrompt, `Initial Files:\n${files.map(f => `--- ${f.path} ---\n${f.content}`).join('\n\n')}` ],
        config: {
          systemInstruction: [
            SESSION_SYSTEM_PROMPT,
            ORCHESTRATOR_SYSTEM_PROMPT
          ],
          responseMimeType: "application/json",
          responseSchema: planSchema,
          temperature: 0.0,
        },
      });

      const text = response.text;
      if (!text) throw new Error("No response text from Gemini");
      
      return JSON.parse(text) as Plan;
    } catch (error) {
      console.error("Plan Generation Error:", error);
      throw error;
    }
  });
};

export const executeTask = async (
  task: { description: string; id: string },
  agent: { name: string; role: string; goal: string; system_prompt?: string },
  planGoal: string,
  context: string
): Promise<AgentOutput> => {
  if (!apiKey) throw new Error("API Key not found");

  const model = "gemini-2.5-flash-lite";

  const agentPrompt = AGENT_SYSTEM_PROMPT_TEMPLATE
    .replace('{name}', agent.name)
    .replace('{role}', agent.role)
    .replace('{goal}', agent.goal)
    .replace('{high_level_goal}', planGoal)
    .replace('{task_description}', task.description)
    .replace('{context}', context);

  return callWithRetry(async () => {
    try {
      const response = await genAI.models.generateContent({
        model,
        contents: [ agentPrompt ],
        config: {
          systemInstruction: [
            SESSION_SYSTEM_PROMPT,
            agent.system_prompt ?? ''
          ],
          responseMimeType: "application/json",
          responseSchema: agentOutputSchema,
          temperature: 0.1,
        }
      });

      const text = response.text;
      if (!text) throw new Error("No response text from Gemini");

      return JSON.parse(text) as AgentOutput;
    } catch (error) {
      console.error(`Task Execution Error (${task.id}):`, error);
      throw error;
    }
  });
};